myapp/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('myapp.views',
    url(r'^$', 'list', name='list'),
    url(r'^list/$', 'list', name='list'),
)

ticktolk/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ticktolk.views.home', name='home'),
                     url(r'^list/$', 'forum.views.list', name='list'),  
url(r'^$', 'forum.views.home', name='home'),
     url(r'^accounts/', include('password_reset.urls')),
	
     url(r'',include('myregistration.urls')),
url(r'^search/$','forum.views.search',name='search'),

url(r'^category/new/$','forum.views.new_category',name='new_category'),
url(r'^category/(?P<slug>[-\w]+)/$','forum.views.get_category',name='get_category'),

url(r'^category/(?P<pk>\d+)/new-topic/$','forum.views.new_thread',name='new_thread'),

url(r'^topics/(?P<slug>[-\w]+)/edit/$','forum.views.edit_thread',name='edit_thread'),
url(r'^topics/(?P<slug>[-\w]+)/$','forum.views.get_thread',name='get_thread'),

url(r'^topics/(\w*)/post/add/$','forum.views.add_post',name='add_post'),
url(r'^topics/(\w*)/quote/$','forum.views.quote_thread',name='quote_thread'),
url(r'^topics/(\w*)/delete/$','forum.views.delete_thread',name='delete_thread'),
    url(r'^admin/', include(admin.site.urls)),
                       
url(r'^(?P<username>\w+)/$','forum.views.user_page',name='user_page'),
                       url(r'^(?P<username>\w+)/edit/$','forum.views.edit_user_page',name='edit_user_page'),

             

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
                            url(r'^media/(?P<path>.*)$', 'serve'),
                            
    )
'''

forum/forms.py
from django import forms
from .models import Thread,Category,Post

from PIL import Image

class AddThreadForm(forms.ModelForm):
    main_post=forms.CharField(widget=forms.Textarea)
   


    class Meta:
        model=Thread
        fields = ['topic', 'main_post','image']

class DocumentForm(forms.Form):
    docfile=forms.FileField(
        label='Select a file my guy')

class QuoteThreadForm(forms.ModelForm):
    quote=forms.CharField(label='quote', max_length=500)
    def clean(self):
        super(QuoteThreadForm, self).clean()
        cleaned_data = self.cleaned_data
        return cleaned_data
    class Meta:
        model=Post
        fields=['quote']

class EditThreadForm(forms.ModelForm):
    def clean(self):
        super(EditThreadForm, self).clean()
        cleaned_data = self.cleaned_data
        return cleaned_data


    class Meta:
        model=Thread
        fields = ['topic', 'main_post']




class AddCategoryForm(forms.ModelForm):


    class Meta:
        model=Category
        fields = ['name', 'description']

class AddPostForm(forms.ModelForm):
    post=forms.CharField(widget=forms.Textarea)
    class Meta:
        model=Post
        fields=['post']

class SearchForm(forms.Form):
    q=forms.CharField()

templates/add_category.html
{% extends "base.html" %}

<div class="container ">
{% block content %}
<form action="." method="POST">
	 {% csrf_token %}
{{ form.as_p }}
<input type="submit">
</form>


{% endblock %}

</div>

</html>

templates/base.html
<html>
<title>ticktolk</title>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/normalize.css">

<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/desktop.css">
{% block external %}
{% endblock %}

<div class="header">
	<a href="/"><h1>ticktolk</h1></a>
	</div>
	
<div class="container">
	{% block heading %}

	{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
	{% endblock %}
	{% block content %}

{% endblock %}

</div>
</html>

templates/edit_thread.html
{% extends "base.html" %}

<div class="container ">
{% block content %}
{{ thread }}

<form enctype="multipart/form-data" action="." method="POST" >

	 {% csrf_token %}
{{ form.as_p }}
<input type="submit">
</form>



{% endblock %}

</div>

</html>

templates/edit_user_page.html
{% extends "base.html" %}

{% block content %}
<script type="text/javascript">
document.gettElementByName('username').onkeydown=function(e){
  e.preventDefault();
}
</script>
<li>  <a href="{% url 'forum.views.user_page' user.username %}">{{ user.username }}</a></li>
{{ user}}


<form enctype="multipart/form-data" action="." method="POST" >

  {% csrf_token %}
  <p>
Username  <input type="text" value={{ user.username}}  name="username" readonly></p>
<p>First name  <input type="text"  name="first_name" placeholder="{{ user.first_name}}"></input></p>
<p>
  Last name <input type="text"  name="last_name" placeholder="{{ user.last_name}}">  </p>
<p>
  Email <input type="email"  name="email" placeholder="{{ user.email }}"></p>

<p><input type="file" name="dp"></p>
<input type="submit" value="Update">
</form>
{% endblock %}

templates/get_category.html
{% extends "base.html" %}

<div class="container ">
{% block content %}
<h4>
<a href="{% url 'forum.views.get_category' category.pk %}">{{ category.name }}</a></h4>

<p>{{ category.description }}</p>

<a href="{% url 'forum.views.new_thread' category.pk %}"><p id="create-new-topic">Create new topic</p></a>

<h3>TOPICS</h3>  
{% if threads %}

{% for thread in threads %}
<a href="{% url 'forum.views.get_thread' thread.pk %}"><li>{{ thread.topic }}</li></a>
{% endfor %}

{% else %}
<p>No topic yet. Be the first to create a topic.</p>
{% endif %}
{% endblock %}

</div>

</html>

templates/get_thread - Copy.html
{% extends "base.html" %}

<div class="container ">
{% block content %}
<div class="get-thread">
<li>
{{ thread.topic }}  <span class="thread-post-username"><a href="{% url 'forum.views.user_page' thread.user.username %}">posted by {{ thread.user }}</a></span></li>


<li>
{{ thread.main_post }}<li>
  {% if user.is_authenticated %}
<ul class="post-mini-nav">

  {% if request.user.username == thread.user.username %}
<li>
<a href="{% url 'forum.views.edit_thread' thread.pk %}">edit</a>
</li>
{% endif %}
{% if request.user.username == thread.user.username %}
<li>
<a href="{% url 'forum.views.delete_thread' thread.pk %}">delete</a></li>
{% endif %}
<li>
<a href="{% url 'forum.views.quote_thread' thread.pk %}">quote</a></li>
</ul>
{% endif %}
<ul class="post-list">
{% if posts %}
{% for post in posts %}
<ul class="single-post">
<li>{{ post.post }}<li>
  <li id="post-author-li"> by <a href="{% url 'forum.views.user_page' post.user.username %}" id="post-author-username">
    {{ post.user.username }}</a></li>
  </ul>
{% endfor %}
{% endif %}
</ul>
</div>
{% if user.is_authenticated %}
<form class="post-form" action="{% url 'forum.views.add_post' thread.pk %}" method="POST">
{% csrf_token %}
{{ new_post_form.as_p }}
<input type="submit" value="Post">
</form>
{% endif %}
</div>

{% endblock %}

</html>

templates/get_thread.html
{% extends "base.html" %}

<div class="container ">
{% block content %}
<div class="get-thread">
<li>
{{ thread.topic }}  <span class="thread-post-username"><a href="{% url 'forum.views.user_page' thread.user.username %}">posted by {{ thread.user }}</a></span></li>

<li>{% if thread.image %}
<img src="{{ thread.image.url }}"  width=500>
{% endif %}</li>
<li>
{{ thread.main_post }}<li>
  {% if user.is_authenticated %}
<ul class="post-mini-nav">

  {% if request.user.username == thread.user.username %}
<li>
<a href="{% url 'forum.views.edit_thread' thread.pk %}">edit</a>
</li>
{% endif %}
{% if request.user.username == thread.user.username %}
<li>
<a href="{% url 'forum.views.delete_thread' thread.pk %}">delete</a></li>
{% endif %}
</ul>
{% endif %}
<ul class="post-list">
{% if posts %}
{% for post in posts %}
<ul class="{{ post.post_type }}">
<li class="">{{ post.post }}<li>

<li>
<a href="{% url 'forum.views.quote_thread' post.pk %}">quote</a></li>



  <li id="post-author-li"> by <a href="{% url 'forum.views.user_page' post.user.username %}" id="post-author-username">
    {{ post.user.username }}</a></li>

  </ul>

{% endfor %}
{% endif %}
</ul>
</div>
{% if user.is_authenticated %}
<form class="post-form" action="{% url 'forum.views.add_post' thread.pk %}" method="POST">
{% csrf_token %}
{{ new_post_form.as_p }}
<input type="submit" value="Post">
</form>
{% endif %}
</div>

{% endblock %}

</html>

templates/homepage.html
<html>
<title>ticktolk</title>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/normalize.css">

<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/desktop.css">

<div class="container">
<div class="header">
  <a href="/"><h1>ticktolk</h1></a>


<ul class="user-nav">
  {% if user.is_authenticated %}
<li> Logged in as  <b><a href="{% url 'forum.views.user_page' user.username %}">{{ user.username }}</a></b></li>
    <li><a href="/logout">Logout</a></li>

    {% else %}
<li>Welcome  <b>Guest!</b></li>
    <li><a href="/login">Login</a></li>

        <li><a href="/register">Register</a></li>

{% endif %}
  </ul>
  </div>

  {% if messages %}

<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<ul class="category-list">
  
{% for category in categories %}
<li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li> 
{% endfor %}
</ul>
<br/>
<ul class="threads-list">

{% if threads %}

{% for thread in threads %}
<a href="{{ thread.get_absolute_url }}"><li>{{ thread.topic }}</li></a>
{% endfor %}
{% endif %}
</ul>


  <form action="/search/" method="GET" id="search-form">

    <input id="id_q" name="q" type="text" required/>

  <input type="submit" id="id_submit" value="search">
  </form>



</div>

</html>

templates/list.html
<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <title>Django File Upload Example</title>
        </head>

        <body>
                <!-- List of uploaded documents -->
                {% if documents %}
                        <ul>
                        {% for document in documents %}
                                <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}
                                <img src="{{ document.docfile.url }}" alt="{{ document.docfile.name }}">
                                </a></li>
                        {% endfor %}
                        </ul>
                {% else %}
                        <p>No documents.</p>
                {% endif %}

                <!-- Upload form. Note enctype attribute! -->
                <form action="{% url "list" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>{{ form.non_field_errors }}</p>
                        <p>{{ form.docfile.label_tag }} </p>
                        <p>
                                {{ form.docfile.errors }}
                                {{ form.docfile }}
                        </p>
                        <p><input type="submit" value="Upload" /></p>
                </form>

        </body>

</html>
~        

templates/new_post.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
    {{ category }}
<form action="." method="POST">
	 {% csrf_token %}
    {{ field.errors }}
{{ form.as_p }}
<input type="submit">
</form>
{% endif %}

{% endblock %}

templates/new_thread.html
{% extends "base.html" %}

{% block content %}

    {{ category }}
<form enctype="multipart/form-data" action="." method="POST" class="new-thread" >
	 {% csrf_token %}
    {{ field.errors }}
{{ form.as_p }}
<input type="submit" value="Create new topic">
</form>


{% endblock %}

templates/quote_thread.html
{% extends "base.html" %}

<div class="container ">
{% block content %}
{{ thread }}

<p>
{{ quoted_text }}
</p>
<form action="." method="POST">
	 {% csrf_token %}
{{ form.as_p }}
<input type="submit">
</form>



{% endblock %}

</div>

</html>

templates/search.html
{% extends "base.html" %}
{% block content %}
<form action="." method="GET">

<input type="search" name="q" required autofocus value="{{query}}"></input>
<input type="submit" value="search">
</form>

<h3>Search Result</h3>
{% if results %}
{% for result in results %}
{{ result.topic }}  {{result.pk}}

<a href="{% url 'forum.views.get_thread' result.slug %}"><li>{{ result.topic }}</li></a>
{% endfor %}
{% else %}
<p> No result for the given query</p>
{% endif %}
{% endblock %}

templates/user_page.html
{% extends "base.html" %}

{% block content %}
<li>  <a href="{% url 'forum.views.user_page' user.username %}">{{ user.username }}</a></li>
{% if pic %}
<img src="{{ pic.url }}" width=200>
{% endif %}
<p>First name: {{ user.first_name }}</p>
<p>Last name: {{ user.last_name }}</p>

{% if request.user.is_authenticated and user == request.user %}
<li>  <a href="{% url 'forum.views.edit_user_page' user.username %}">edit</a></li>
{% endif %}
<h3>Topics</h3>
	{% if threads %}
{% for thread in threads %}

<a href="{% url 'forum.views.get_thread' thread.slug %}"><li>{{ thread.topic }}</li></a>
{% endfor %}
{% else %}
<li>You have not created a topic yet</li>
{% endif %}


{% endblock %}